spring.application.name=InVera

# ================= DATABASE =================
spring.datasource.url=jdbc:postgresql://localhost:5433/invera
spring.datasource.username=postgres
spring.datasource.password=96981311

# ================= JPA =================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ================= SERVER =================
server.port=8081

# ================= JWT =================
# HS512 requires a MINIMUM of 64 characters
app.jwt.secret=InVeraJwtSecretKey_ChangeThis_ToAtLeast64CharactersLongForHS512!!!
app.jwt.expiration=86400000

# ================= EMAIL =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nassibmim25@gmail.com
spring.mail.password=ojxa omyb dzyy rrie
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
