spring.application.name=InVera


# ================= BASE ERP (template) =================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ================= BASE PLATEFORME (SaaS) =================
platform.datasource.url=${PLATFORM_DB_URL}
platform.datasource.username=${PLATFORM_DB_USERNAME}
platform.datasource.password=${PLATFORM_DB_PASSWORD}
platform.datasource.driver-class-name=org.postgresql.Driver

# ================= JPA =================
spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ================= SERVER =================
server.port=8081

# ================= JWT =================
app.jwt.secret=InVeraJwtSecretKey_ChangeThis_ToAtLeast64CharactersLongForHS512!!!
app.jwt.expiration=86400000
app.frontend.activation-url=http://localhost:5173/create-password

# ================= EMAIL =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nassibmim25@gmail.com
spring.mail.password=ojxaomybdzyyrrie
spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

logging.level.org.springframework.security=DEBUG
logging.level.org.erp.invera=DEBUG
spring.jpa.properties.hibernate.default_batch_fetch_size=20
